export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESSFULLY = 'ADD_PRODUCT_SUCCESSFULLY';
export const ADD_PRODUCT_ERR = 'ADD_PRODUCT_ERR';

export const DOWNLOAD_PRODUCTS = 'DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESSFULLY = 'DOWNLOAD_PRODUCTS_SUCCESSFULLY';
export const DOWNLOAD_PRODUCTS_ERR = 'DOWNLOAD_PRODUCTS_ERR';

export const GET_PRODUCT_TO_DELETE = 'GET_PRODUCT_TO_DELETE';
export const PRODUCT_DELETED_SUCCESSFULLY = 'PRODUCT_DELETED_SUCCESSFULLY';
export const PRODUCT_NO_DELETED_ERR = 'PRODUCT_NO_DELETED_ERR';

export const GET_PRODUCT_TO_EDIT = 'GET_PRODUCT_TO_EDIT';
export const INIT_TO_EDIT_PRODUCT = 'INIT_TO_EDIT_PRODUCT';
export const PRODUCT_EDITED_SUCCESSFULLY = 'PRODUCT_EDITED_SUCCESSFULLY';
export const PRODUCT_NO_EDITED_ERR = 'PRODUCT_NO_EDITED_ERR';