export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESSFULLY = 'ADD_PRODUCT_SUCCESSFULLY';
export const ADD_PRODUCT_ERR = 'ADD_PRODUCT_ERR';

export const DOWNLOAD_PRODUCTS = 'DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESSFULLY = 'DOWNLOAD_PRODUCTS_SUCCESSFULLY';
export const DOWNLOAD_PRODUCTS_ERR = 'DOWNLOAD_PRODUCTS_ERR';